### ISSUE TITLE
Tests for all screens, actions, forms and features

### ISSUE THREAD

**Issue by himdel** [himdel/ansible-hub-ui#1]
Epic [AAH-615](https://issues.redhat.com/browse/AAH-615)
checklists for various kinds of screens in https://github.com/ansible/ansible-hub-ui/pull/1149

### Screens, forms, actions

* [x] Collections > Collections
  * [x] list screen
    * [x] repo switcher
    * [x] cards/list
  * [x] detail screen
    * [x] tab Install
      * [x] download tarball
      * [x] tags
      * [x] requires ansible
    * [x] tab Documentation
      * [x] search
    * [x] tab Contents (no data from galaxykit)
      * [ ] search
      * [ ] list
    * [x] tab Import log 
    * [x] tab Dependencies
      * [ ] test a collection with dependencies (no data from galaxykit)
    * [ ] version switcher (no data from galaxykit)
    * [x] action Delete version
    * [x] action Delete collection
* [ ] Collections > Namespaces
  * [x] list screen - my namespaces "filter"
    * [x] action Create - form
  * [ ] detail screen (View collections)
    * [x] tab Collections
      * [x] list screen like tests for the list of collections
      * [x] list action Upload new version - form, checking filename, imports redirect
      * [x] list action Deprecate - deprecated label on reload
    * [ ] tab CLI Configuration
    * [ ] tab Resources - only visible after Edit namespaces, Edit resources (edit namespaces is still broken)
    * [x] action Upload collection
      * [ ] checking filename (like Upload new version but compares namespace portion only)
    * [x] action Edit namespace - form
      * [x] tab Edit details - form
        * [x] test owners
        * [ ] bad logo url
          * [ ] verify on detail screen
        * [x] links
          * [x] verify on detail screen
      * [x] tab Edit resources
        * [ ] verify on detail screen Resources tab
    * [x] action Delete namespace
      * [ ] can only delete when empty
    * [ ] action Imports - My Imports screen - namespace filter, filter filter, paging, log
* [ ] Collections > Repository Management
  * [ ] tab Local - list screen
    * [ ] list action Get token
    * [ ] expand CLI configuration
    * [ ] copy
  * [ ] tab Remote - list screen
    * [ ] list action Configure/Edit
      * [ ] `RemoteForm` form, has 3 collection modes by type (+ a registry new/edit mode for EE)
    * [ ] list action Sync - sync status updates
* [x] Collections > API Token
  * [x] Load token button, copy
  * [ ] (insights) more info
  * [ ] (keycloak) token expiration info
* [ ] Collections > Approval
  * [ ] list screen
    * [ ] version clickthrough
    * [ ] default Needs Review filter
    * [ ] list action Approve
    * [ ] list action Reject
    * [ ] list action View import logs
* [x] Execution Environments > Execution Environments
  * [x] list screen
    * [x] adding a local EE via docker/podman push
    * [ ] action Add execution environment - form, adding a remote EE
    * [ ] list action Edit - form
      * [ ] readonly name
      * [ ] different for local/remote
    * [x] list action Use in Controller - form, with list
    * [ ] list action Delete
    * [ ] (remote) list action Sync from registry - task notification
  * [x] detail screen
    * [x] tab Detail
      * [x] action Add/Edit (readme) - form
        * [x] verify it updates
    * [ ] tab Activity
      * [ ] click through to Manifest screen (below)
    * [ ] tab Images - list screen
      * [ ] click through to Manifest screen (below)
      * [ ] list action Manage tags - form
      * [ ] list action Use in Controller (same as from list view, preselected tag/digest)
      * [ ] list action Delete
      * [ ] (manifest list items) expander with clickthroughs and OS/Arch, no layers count or size in main table
    * [ ] screen Manifest
      * [ ] list of layers, clicking changes command & environment
      * [ ] link to Activity when opened on a manifest list
    * [x] action Edit - same as from list view
      * [ ] different between local/remote
    * [x] action Use in Controller - same as from list view
    * [ ] (remote) action Sync from registry - same as from list view, verify it updates last synced in header
* [ ] Execution Environments > Remote Registries
  * [ ] list screen
    * [ ] action Add remote registry - `RemoteForm` form (shared with collection remotes, different fields)
    * [ ] list action Sync from registry - task notification
    * [ ] list action Edit - same `RemoteForm`, name readonly
    * [ ] list action Delete
    * [ ] list action Index execution environments - only available for registry.redhat.io
* [ ] Task Management
  * [ ] list screen
    * [ ] status, nice name popup
  * [ ] detail screen
    * [ ] link through to parent/children (syncing registry creates a task with N children per number of remote containers from there)u
    * [ ] Progress messages (remote ee sync that worked) / Error message (collection or remote ee sync from nonexistent registry)
    * [ ] both names
* [x] Documentation - external link
* [ ] User Access > Users
  * [ ] list screen
    * [x] action Create - form
      * [ ] test superuser switcher 
  * [ ] detail screen
    * [ ] actually the same screen as user Create, user Edit, and nav > My profile, with slight differences
    * [ ] action Edit - form above
    * [x] action Delete
      * [ ] and superuser logic 
* [x] User Access > Groups
  * [x] list screen
    * [x] action Create - form
    * [x] list action Delete
  * [x] detail screen
    * [x] tab Permissions
      * [x] action Edit - form
        * [ ] other actions disabled during
    * [x] tab Users
      * [x] action Add - form
      * [ ] list screen
      * [x] list action Remove
      * [ ] user detail clickthrough
    * [ ] action Delete

### Features

* [x] login, navbar menu
  * [x] Customer Support, Training, About modal
  * [x] username
    * [x] My profile
    * [ ] Logout
* [x] menu - left nav
  * [ ] hiding by the nav-toggle
* [x] view-only
* [ ] keycloak
* [ ] insights
* [ ] required approval (AAH-628)
* [ ] empty states (no data, filter, unauthorized)
* [ ] error states (404, 500) (https://github.com/ansible/ansible-hub-ui/pull/1115#issuecomment-1042020478)

### TODO

* finish checking checkboxes (20/28 remote_registry.js)
* create jira issues for unchecked checkboxes where missing

**Comment by himdel** [comment]
Cc @zitanemeckova , I think this is all of them :) (I'll go through the checkboxes on Monday)
