### ISSUE TITLE
New branch checklist

### ISSUE THREAD

**Issue by himdel** [himdel/ansible-hub-ui#3]
#### Github labels:

`backport-X.Y` & `backported-X.Y` in https://github.com/ansible/ansible-hub-ui/labels & https://github.com/ansible/galaxy_ng/labels

#### Update dependabot (on master):

add an entry for the new release `.github/dependabot.yml`, `.github/labeler.yml`

#### Bump version for python tooling (both master and new branch):

bump version in `ansible-hub-ui/__init__.py` on both master and new branch

#### Update workflows

`.github/workflows/i18n.yml` needs updating with the new branch (do skip 4.2 and 4.3)

#### Update workflow list by branches in README (master)

`README.md` probably needs a new entry in the branch list

### Cleanup in the new stable branch

Drop pretty much anything from `.github/` except for workflows that apply to `pull_request:` or `push:` (or `tags:`) for that branch . (`dependabot`, `patchback` and cron workflows run from master)

Update README to drop things only maintained in master README - workflows and deploying sections.

Drop husky (to prevent different branches installing different versions, and drop ancient husky deps)

Ensure `.github/workflows/cypress.yml` installs galaxykit from pypi, not github for stable branches. (`pip install git+https://github.com/ansible/galaxykit.git` -> `pip install galaxykit`)

Update cypress.yml build step - change `ghcr.io/pulp/pulp-ci-centos:latest` to the permanent version of the latest tag (https://hub.docker.com/r/pulp/pulp-ci-centos/tags .. as in latest -> 3.15).

Drop insights and community specific bits

Update access.redhat.*documentation links to point to the right version. (https://github.com/ansible/ansible-hub-ui/pull/3422)

### Previous last stable version

Ensure `.github/workflows/cypress.yml` installs a specific version of galaxykit from pypi, not latest. (`pip install galaxykit` -> `pip install galaxykit==0.7.0`)

**Comment by himdel** [comment]
Note: when changing the checklist, update [confluence](https://docs.engineering.redhat.com/display/AUTOHUB/Release+Processes) as well.

**Comment by himdel** [comment]
`stable-4.5` post-branching list:

version bumps:
* https://github.com/ansible/ansible-hub-ui/pull/1891
* https://github.com/ansible/ansible-hub-ui/commit/50022b14ece56eb1945a7859733ebf0281ab7a84

labels `backport-4.5` & `backported-4.5`:
* https://github.com/ansible/ansible-hub-ui/labels
* https://github.com/ansible/galaxy_ng/labels

dependabot:
* https://github.com/ansible/ansible-hub-ui/pull/1855

i18n workflow:
* https://github.com/ansible/ansible-hub-ui/pull/1916

README:
* https://github.com/ansible/ansible-hub-ui/pull/1915

cleanup in `stable-4.5`:
* https://github.com/ansible/ansible-hub-ui/pull/1921

galaxykit in `stable-4.5`:
* https://github.com/ansible/ansible-hub-ui/pull/1969

galaxykit in `stable-4.4`:
* https://github.com/ansible/ansible-hub-ui/pull/1968

pulp-ci-centos:
* https://github.com/ansible/ansible-hub-ui/pull/2498

**Comment by himdel** [comment]
`stable-4.6` post-branching list:

version bumps:
  * https://github.com/ansible/galaxy_ng/pull/1459 - bump galaxy_ng master to 4.7.0dev
  * https://github.com/ansible/galaxy_ng/pull/1461 - bump galaxy_ng stable-4.6 to 4.6.0b1
  * https://github.com/ansible/ansible-hub-ui/pull/2603 - bump ansible-hub-ui stable-4.6 to 4.6.0b1
  * https://github.com/ansible/ansible-hub-ui/pull/2604 - bump ansible-hub-ui master to 4.7.0dev

labels `backport-4.6` & `backported-4.6`:
  * https://github.com/ansible/ansible-hub-ui/labels
  * https://github.com/ansible/galaxy_ng/labels
  * `backport-4.6` "This PR should be backported to stable-4.6 (2.3)"
  * `backported-4.6` "This PR has been backported to stable-4.6 (2.3)"

dependabot, i18n workflow, README:
  * https://github.com/ansible/ansible-hub-ui/pull/2621

cleanup in `stable-4.6`:
  * `.github/workflows/` - leaving only `backported-labels`, `cypress` (and `scripts/`), `pr-checks` and `stable-release`
  * `.github/` - leaving only `workflows/`
  * `package.json` - remove `husky` from deps and the `husky` config section, run `npm install` afterwards to update the lockfile
  * `README.md` - drop "Develop in Insights Mode", "Deploying", "How it works", "Workflows" and "Insights Components" sections
  * `.cloud-stage-cron.enabled` - rm
  * `.travis/` - rm whole
  * `build_deploy.sh`, `ci.sh`, `pr_check.sh` - rm
  * https://github.com/ansible/ansible-hub-ui/pull/2622

galaxykit46:
  * set to `pip install galaxykit`
  * https://github.com/ansible/ansible-hub-ui/pull/2622

galaxykit45:
  * set to `pip install galaxykit==0.8.0`
  * already happened in #1969

pulp-ci-centos:
* https://github.com/ansible/ansible-hub-ui/pull/2622

**Comment by himdel** [comment]
`stable-4.7` post-branching list:

* [x] labels
* [x] bump master to 4.8 (ui) - https://github.com/ansible/ansible-hub-ui/pull/3469
* [x] bump master to 4.8 (api) - https://github.com/ansible/galaxy_ng/pull/1667
* [x] bump 4.7 to b1 (ui) - https://github.com/ansible/ansible-hub-ui/pull/3500
* [x] bump 4.7 to b1 (api) - https://github.com/ansible/galaxy_ng/pull/1666
* [x] update master README, workflows - https://github.com/ansible/ansible-hub-ui/pull/3469
* [x] clean up dead code in 4.7 - https://github.com/ansible/ansible-hub-ui/pull/3500 & https://github.com/ansible/ansible-hub-ui/pull/3502
* [x] fix version of galaxykit in 4.6 - https://github.com/ansible/ansible-hub-ui/pull/3503
* [x] fix version of galaxykit in 4.7 - https://github.com/ansible/ansible-hub-ui/pull/3500
* (pulp-ci-centos no longer relevant with oci-env)
* [ ] (once docs exists for 4.7) - update access.rh links
* (checked 4.7 oci-env uses 4.7 backend, does since https://github.com/ansible/ansible-hub-ui/pull/2822)
