### ISSUE TITLE
screens checklist

### ISSUE THREAD

**Issue by himdel** [himdel/ansible-hub-ui#7]
updated 2023-12-08
new: 77%, open: 14%, done: 7%

* [ ] AAH-2381 ui framework: fix pagination with l10n (`Task`; `Backlog`)
* [ ] AAH-2398 Hub > Additional tasks (placeholder) (`Epic`; `Refinement`)
* [ ] AAH-2399 Hub > Support authentication (`Epic`; `Backlog`)
* [ ] AAH-2400 Hub > support community / galaxy beta (`Epic`; `Backlog`)
* [ ] AAH-2401 Hub > Support insights mode (`Epic`; `Backlog`)
* [ ] AAH-2402 Hub > Framework changes necessary for hub (`Epic`; `Refinement`)
* [ ] AAH-2411 Collection version search API filter enhancements (`Story`; `Backlog`)
* [ ] AAH-2412 API to retrieve predefined categories of collections for the new Hub Dashboard UI (`Story`; `Backlog`)
* [ ] AAH-2447 Hub > Collections (`Epic`; `In Progress`)
* [x] AAH-2448 Collections > action Delete collection (`Task`; `Closed`)
* [x] AAH-2449 Collections > action Delete version (`Task`; `Closed`)
* [x] AAH-2450 Collections > action Remove collection from repository (`Task`; `Closed`)
* [x] AAH-2451 Collections > action Remove version from repository (`Task`; `Closed`)
* [ ] AAH-2452 Collections > action Sign collection (`Task`; `Backlog`)
* [ ] AAH-2453 Collections > action Sign version (`Task`; `Backlog`)
* [x] AAH-2454 Collections > action Deprecate (`Task`; `Closed`)
* [x] AAH-2455 Collections > action Upload new version (`Task`; `Closed`)
* [x] AAH-2456 Collections > action Approve (`Task`; `Closed`)
* [x] AAH-2457 Collections > action Copy version to repositories (`Task`; `Closed`)
* [ ] AAH-2458 Collections > tab Install (`Task`; `In Progress`)
* [ ] AAH-2459 Collections > tab Install > Download tarball (`Task`; `Backlog`)
* [ ] AAH-2460 Collections > tab Install > Show the signature (`Task`; `Backlog`)
* [ ] AAH-2461 Collections > tab Documentation (`Task`; `In Progress`)
* [ ] AAH-2462 Collections > tab Contents (`Task`; `Backlog`)
* [ ] AAH-2463 Collections > tab Import log (`Task`; `Backlog`)
* [ ] AAH-2464 Collections > tab Dependencies (`Task`; `Backlog`)
* [ ] AAH-2465 Collections > tab Distributions (`Task`; `Backlog`)
* [ ] AAH-2466 Collections > version picker (`Task`; `Backlog`)
* [ ] AAH-2467 Collections > typeahead filter (`Task`; `Backlog`)
* [ ] AAH-2468 Hub > Namespaces (`Epic`; `In Progress`)
* [ ] AAH-2469 Namespaces > action Create (`Task`; `Code Review`)
* [x] AAH-2470 Namespaces > action Upload collection (`Task`; `Closed`)
* [ ] AAH-2471 Namespaces > action Edit namespace (`Task`; `Code Review`)
* [ ] AAH-2472 Namespaces > action Delete namespace (`Task`; `Code Review`)
* [ ] AAH-2473 Namespaces > action Imports (`Task`; `Backlog`)
* [ ] AAH-2474 Namespaces > action Sign all collections (`Task`; `Backlog`)
* [ ] AAH-2475 Namespaces > action Ansible Lightspeed settings (`Task`; `Backlog`)
* [ ] AAH-2476 Namespaces > tab Collections (`Task`; `Backlog`)
* [ ] AAH-2477 Namespaces > tab CLI configuration (`Task`; `In Progress`)
* [ ] AAH-2478 Namespaces > tab Access (`Task`; `Backlog`)
* [ ] AAH-2479 Hub > Repositories (`Epic`; `In Progress`)
* [ ] AAH-2480 Repositories > action Add repository (`Task`; `In Progress`)
* [ ] AAH-2481 Repositories > action Edit (`Task`; `Backlog`)
* [ ] AAH-2482 Repositories > action Sync (`Task`; `Backlog`)
* [ ] AAH-2483 Repositories > action Copy CLI configuration (`Task`; `Backlog`)
* [ ] AAH-2484 Repositories > action Delete (`Task`; `Backlog`)
* [ ] AAH-2485 Repositories > tab Details (`Task`; `Backlog`)
* [ ] AAH-2486 Repositories > tab Access (`Task`; `Backlog`)
* [ ] AAH-2487 Repositories > tab Collection versions (`Task`; `Backlog`)
* [ ] AAH-2488 Repositories > tab Collection versions > action Add collection (`Task`; `Backlog`)
* [ ] AAH-2489 Repositories > tab Collection versions > action Remove (`Task`; `Backlog`)
* [ ] AAH-2490 Repositories > tab Versions (`Task`; `Backlog`)
* [ ] AAH-2491 Repositories > tab Versions > action Revert to version (`Task`; `Backlog`)
* [ ] AAH-2492 Hub > Remotes (`Epic`; `In Progress`)
* [ ] AAH-2493 Remotes > action Add remote (`Task`; `In Progress`)
* [ ] AAH-2494 Remotes > action Edit (`Task`; `In Progress`)
* [ ] AAH-2495 Remotes > action Delete (`Task`; `In Progress`)
* [ ] AAH-2496 Remotes > tab Details (`Task`; `In Progress`)
* [ ] AAH-2497 Remotes > tab Access (`Task`; `Backlog`)
* [ ] AAH-2498 Hub > API token - standalone (`Epic`; `Backlog`)
* [ ] AAH-2499 API token - standalone > action Load token (`Task`; `Backlog`)
* [ ] AAH-2500 API token - standalone > SSO info when sso (`Task`; `Backlog`)
* [ ] AAH-2501 API token - insights (`Task`; `Backlog`)
* [ ] AAH-2502 API token - insights > action Load token (`Task`; `Backlog`)
* [ ] AAH-2503 API token - insights > insights info (`Task`; `Backlog`)
* [ ] AAH-2504 Hub > Approval (`Epic`; `In Progress`)
* [x] AAH-2505 Approval > action Approve / Sign and approve (`Task`; `Closed`)
* [x] AAH-2506 Approval > action Reject (`Task`; `Closed`)
* [ ] AAH-2507 Approval > action View Import Logs (`Task`; `Backlog`)
* [ ] AAH-2508 Approval > action Upload signature (`Task`; `Backlog`)
* [ ] AAH-2509 Hub > My imports (`Epic`; `Backlog`)
* [ ] AAH-2510 Hub > Execution Environments (`Epic`; `In Progress`)
* [x] AAH-2511 Execution Environments > action Add execution environment (`Task`; `Closed`)
* [ ] AAH-2512 Execution Environments > action Push container image (`Task`; `Backlog`)
* [x] AAH-2513 Execution Environments > action Edit (local/remote) (`Task`; `Closed`)
* [x] AAH-2514 Execution Environments > action Sync from registry (`Task`; `Closed`)
* [ ] AAH-2515 Execution Environments > action Use in Controller (`Task`; `In Progress`)
* [x] AAH-2516 Execution Environments > action Delete (`Task`; `Closed`)
* [ ] AAH-2517 Execution Environments > action Sign* (`Task`; `Backlog`)
* [ ] AAH-2518 Execution Environments > tab Detail (`Task`; `Backlog`)
* [ ] AAH-2519 Execution Environments > tab Detail > action Add/Edit README (`Task`; `Backlog`)
* [ ] AAH-2520 Execution Environments > tab Activity (`Task`; `Backlog`)
* [ ] AAH-2521 Execution Environments > tab Activity > Image layers (`Task`; `Backlog`)
* [ ] AAH-2522 Execution Environments > tab Images (`Task`; `Backlog`)
* [ ] AAH-2523 Execution Environments > tab Images > action Use in Controller (`Task`; `Backlog`)
* [ ] AAH-2524 Execution Environments > tab Images > action Delete (`Task`; `Backlog`)
* [ ] AAH-2525 Execution Environments > tab Images > action Manage tags (`Task`; `Backlog`)
* [ ] AAH-2526 Execution Environments > tab Access (`Task`; `Backlog`)
* [ ] AAH-2527 Hub > Remote Registries (`Epic`; `In Progress`)
* [ ] AAH-2528 Remote Registries > action Add remote registry (`Task`; `In Progress`)
* [ ] AAH-2529 Remote Registries > action Edit (`Task`; `In Progress`)
* [ ] AAH-2530 Remote Registries > action Delete (`Task`; `In Progress`)
* [ ] AAH-2531 Remote Registries > action Index execution environments (`Task`; `Backlog`)
* [ ] AAH-2532 Remote Registries > action Sync from registry (`Task`; `In Progress`)
* [ ] AAH-2533 Hub > Task Management (`Epic`; `In Progress`)
* [x] AAH-2534 Task Management > action Stop task (`Task`; `Closed`)
* [ ] AAH-2535 Hub > Signature Keys (`Epic`; `Backlog`)
* [ ] AAH-2536 Signature Keys > action Download key (`Task`; `Backlog`)
* [ ] AAH-2537 Hub > Documentation and navbar links (`Epic`; `Backlog`)
* [ ] AAH-2538 Dashboard (`Task`; `Backlog`)
* [ ] AAH-2539 Hub > About modal (`Epic`; `Backlog`)
* [ ] AAH-2540 Hub > Standalone Roles (`Task`; `Backlog`)
* [ ] AAH-2541 Standalone Roles > tab Install (`Task`; `Backlog`)
* [ ] AAH-2542 Standalone Roles > tab Documentation (`Task`; `Backlog`)
* [ ] AAH-2543 Standalone Roles > tab Versions (`Task`; `Backlog`)
* [ ] AAH-2544 Hub > Standalone Role Namespaces (`Task`; `Backlog`)
* [ ] AAH-2545 Standalone Role Namespaces > action Ansible Lightspeed settings (`Task`; `Backlog`)
* [ ] AAH-2546 Hub > tab Access (`Epic`; `Refinement`)
* [ ] AAH-2547 tab Access > action Select a group/user (`Task`; `Backlog`)
* [ ] AAH-2548 tab Access > action Remove group/user (`Task`; `Backlog`)
* [ ] AAH-2549 tab Access > action Add roles (`Task`; `Backlog`)
* [ ] AAH-2550 tab Access > action Remove role (`Task`; `Backlog`)
* [ ] AAH-2551 Hub > User me (`Epic`; `Backlog`)
* [ ] AAH-2552 Hide login screen for anonymous login (`Task`; `Backlog`)
* [ ] AAH-2553 Customizable login redirect target (`Task`; `Backlog`)
* [ ] AAH-2554 Hub > Users (`Epic`; `Refinement`)
* [ ] AAH-2555 Users > action Create (`Task`; `Backlog`)
* [ ] AAH-2556 Users > action Edit (`Task`; `Backlog`)
* [ ] AAH-2557 Users > action Delete (`Task`; `Backlog`)
* [ ] AAH-2558 Hub > Groups (`Epic`; `Refinement`)
* [ ] AAH-2559 Groups > action Create (`Task`; `Backlog`)
* [ ] AAH-2560 Groups > action Delete (`Task`; `Backlog`)
* [ ] AAH-2561 Groups > tab Access (`Task`; `Backlog`)
* [ ] AAH-2562 Groups > tab Access > action Add roles (`Task`; `Backlog`)
* [ ] AAH-2563 Groups > tab Access > action Remove role (`Task`; `Backlog`)
* [ ] AAH-2564 Groups > tab Users (`Task`; `Backlog`)
* [ ] AAH-2565 Groups > tab Users > action Add (`Task`; `Backlog`)
* [ ] AAH-2566 Groups > tab Users > action Remove (`Task`; `Backlog`)
* [ ] AAH-2567 Hub > Roles (`Epic`; `Refinement`)
* [ ] AAH-2568 Roles > action Add roles (`Task`; `Code Review`)
* [ ] AAH-2569 Roles > action Edit (`Task`; `Code Review`)
* [ ] AAH-2570 Roles > action Delete (`Task`; `Release Pending`)
* [ ] AAH-2571 Roles > builtin/editable (`Task`; `Code Review`)
* [ ] AAH-2572 Roles > permission selector (`Task`; `Code Review`)
* [ ] AAH-2649 404 dispatch for old-galaxy link compatibility (`Task`; `Backlog`)
* [ ] AAH-2662 Update value of CERTIFIED_REPO constant in Insights mode (`Task`; `New`)
* [ ] AAH-2669 Having collections in various categories as part of installer for Day 0 view of the hub dashboard (`Story`; `New`)
* [ ] AAH-2688 Hub > Builder UI (`Epic`; `Refinement`)
* [ ] AAH-2706 Hub > Write developer docs for the new UI (`Epic`; `Backlog`)
* [ ] AAH-2764 UI wizard (`Task`; `New`)
* [ ] AAH-2778 UI wizard in CRC (`Task`; `New`)
* [ ] AAH-2851 Remote Registry > tab Details (`Task`; `In Progress`)
* [ ] AAH-2883 Any changes to Old UI that need to be ported to New Platform UI for done epics [Do not move to Done] (`Epic`; `In Progress`)
* [ ] AAH-2893 test Hub > Collections (`Task`; `New`)
* [ ] AAH-2894 Collections > test Delete collection (`Task`; `New`)
* [ ] AAH-2895 Collections > test Delete version (`Task`; `New`)
* [ ] AAH-2896 Collections > test Remove collection from repository (`Task`; `New`)
* [ ] AAH-2897 Collections > test Remove version from repository (`Task`; `New`)
* [ ] AAH-2898 Collections > test Sign collection (`Task`; `New`)
* [ ] AAH-2899 Collections > test Sign version (`Task`; `New`)
* [ ] AAH-2900 Collections > test Deprecate (`Task`; `New`)
* [ ] AAH-2901 Collections > test Upload new version (`Task`; `New`)
* [ ] AAH-2902 Collections > test Approve (`Task`; `New`)
* [ ] AAH-2903 Collections > test Copy version to repositories (`Task`; `New`)
* [ ] AAH-2904 test Hub > Namespaces (`Task`; `New`)
* [ ] AAH-2905 Namespaces > test Create (`Task`; `New`)
* [ ] AAH-2906 Namespaces > test Upload collection (`Task`; `New`)
* [ ] AAH-2907 Namespaces > test Edit namespace (`Task`; `New`)
* [ ] AAH-2908 Namespaces > test Delete namespace (`Task`; `New`)
* [ ] AAH-2909 Namespaces > test Imports (`Task`; `New`)
* [ ] AAH-2910 Namespaces > test Sign all collections (`Task`; `New`)
* [ ] AAH-2911 Namespaces > test Ansible Lightspeed settings (`Task`; `New`)
* [ ] AAH-2912 test Hub > Repositories (`Task`; `New`)
* [ ] AAH-2913 Repositories > test Add repository (`Task`; `New`)
* [ ] AAH-2914 Repositories > test Edit (`Task`; `New`)
* [ ] AAH-2915 Repositories > test Sync (`Task`; `New`)
* [ ] AAH-2916 Repositories > test Copy CLI configuration (`Task`; `New`)
* [ ] AAH-2917 Repositories > test Delete (`Task`; `New`)
* [ ] AAH-2918 Repositories > tab Collection versions > test Add collection (`Task`; `New`)
* [ ] AAH-2919 Repositories > tab Collection versions > test Remove (`Task`; `New`)
* [ ] AAH-2920 Repositories > tab Versions > test Revert to version (`Task`; `New`)
* [ ] AAH-2921 test Hub > Remotes (`Task`; `New`)
* [ ] AAH-2922 Remotes > test Add remote (`Task`; `New`)
* [ ] AAH-2923 Remotes > test Edit (`Task`; `New`)
* [ ] AAH-2924 Remotes > test Delete (`Task`; `New`)
* [ ] AAH-2925 test Hub > API token - standalone (`Task`; `New`)
* [ ] AAH-2926 test Hub > Approval (`Task`; `New`)
* [ ] AAH-2927 Approval > test Approve / Sign and approve (`Task`; `New`)
* [ ] AAH-2928 Approval > test Reject (`Task`; `New`)
* [ ] AAH-2929 Approval > test View Import Logs (`Task`; `New`)
* [ ] AAH-2930 Approval > test Upload signature (`Task`; `New`)
* [ ] AAH-2931 test Hub > My imports (`Task`; `New`)
* [ ] AAH-2932 test Hub > Execution Environments (`Task`; `New`)
* [ ] AAH-2933 Execution Environments > test Add execution environment (`Task`; `New`)
* [ ] AAH-2934 Execution Environments > test Push container image (`Task`; `New`)
* [ ] AAH-2935 Execution Environments > test Edit (local/remote) (`Task`; `New`)
* [ ] AAH-2936 Execution Environments > test Sync from registry (`Task`; `New`)
* [ ] AAH-2937 Execution Environments > test Use in Controller (`Task`; `New`)
* [ ] AAH-2938 Execution Environments > test Delete (`Task`; `New`)
* [ ] AAH-2939 Execution Environments > test Sign* (`Task`; `New`)
* [ ] AAH-2940 Execution Environments > tab Detail > test Add/Edit README (`Task`; `New`)
* [ ] AAH-2941 Execution Environments > tab Images > test Delete (`Task`; `New`)
* [ ] AAH-2942 Execution Environments > tab Images > test Manage tags (`Task`; `New`)
* [ ] AAH-2943 test Hub > Remote Registries (`Task`; `New`)
* [ ] AAH-2944 Remote Registries > test Add remote registry (`Task`; `New`)
* [ ] AAH-2945 Remote Registries > test Edit (`Task`; `New`)
* [ ] AAH-2946 Remote Registries > test Delete (`Task`; `New`)
* [ ] AAH-2947 Remote Registries > test Sync from registry (`Task`; `New`)
* [ ] AAH-2948 test Hub > Task Management (`Task`; `New`)
* [ ] AAH-2949 test Hub > Signature Keys (`Task`; `New`)
* [ ] AAH-2950 test Hub > Standalone Roles (`Task`; `New`)
* [ ] AAH-2951 test Hub > Standalone Role Namespaces (`Task`; `New`)
* [ ] AAH-2952 RBAC: Collections (`Task`; `New`)
* [ ] AAH-2953 RBAC: Namespaces (`Task`; `New`)
* [ ] AAH-2954 RBAC: Repositories (`Task`; `New`)
* [ ] AAH-2955 RBAC: Remotes (`Task`; `New`)
* [ ] AAH-2956 RBAC: API token - standalone (`Task`; `New`)
* [ ] AAH-2957 RBAC: Approval (`Task`; `New`)
* [ ] AAH-2958 RBAC: My imports (`Task`; `New`)
* [ ] AAH-2959 RBAC: Execution Environments (`Task`; `New`)
* [ ] AAH-2960 RBAC: Remote Registries (`Task`; `New`)
* [ ] AAH-2961 RBAC: Task Management (`Task`; `New`)
* [ ] AAH-2962 RBAC: Standalone Roles (`Task`; `New`)
* [ ] AAH-2988 Update Bulk Actions to deal with the task system (`Task`; `New`)
* [ ] AAH-2991 Collection - refactor tabs to be according to new approach (`Task`; `Code Review`)
* [ ] AAH-2993 Error handling pattern (`Task`; `New`)
* [ ] AAH-2994 Multirequest actions pattern (`Task`; `New`)
* [ ] AAH-2995 Remotes > add signed only and sync dependencies (`Task`; `Code Review`)

**Comment by himdel** [comment]
(scroll right..); AAH-3007

| url | `page` / `offset` | `page_size` / `limit` | `sort` / `order_by` / `ordering` | `data` / `results` | `count` / `meta.count` |
|-|-|-|-|-|-|
|`_ui/v1/ai_deny_index/`|`offset`|`limit`|`sort`|`results`|**`count`**|
|`_ui/v1/controllers/`|`offset`|`limit`|`sort`|`data`|`meta.count`|
|`_ui/v1/execution-environments/registries/`|`offset`|`limit`|`sort`|`data`|`meta.count`|
|`_ui/v1/execution-environments/remotes/`|`offset`|`limit`|`sort`|`data`|`meta.count`|
|`_ui/v1/groups/`|`offset`|`limit`|`sort`|`data`|`meta.count`|
|`_ui/v1/imports/collections/`|`offset`|`limit`|`sort`|`data`|`meta.count`|
|`_ui/v1/my-distributions/`|`offset`|`limit`|`sort`|`data`|`meta.count`|
|`_ui/v1/my-namespaces/`|`offset`|`limit`|`sort`|`data`|`meta.count`|
|`_ui/v1/my-synclists/`|`offset`|`limit`|`sort`|`data`|`meta.count`|
|`_ui/v1/namespaces/`|`offset`|`limit`|`sort`|`data`|`meta.count`|
|`_ui/v1/tags/`|`offset`|`limit`|`sort`|`data`|`meta.count`|
|`_ui/v1/users/`|`offset`|`limit`|`sort`|`data`|`meta.count`|
|`pulp/api/v3/content/ansible/collection_signatures/`|`offset`|`limit`|`ordering`|`results`|`count`|
|`pulp/api/v3/distributions/ansible/ansible/`|`offset`|`limit`|`ordering`|`results`|`count`|
|`pulp/api/v3/distributions/container/container/`|`offset`|`limit`|`ordering`|`results`|`count`|
|`pulp/api/v3/groups/`|`offset`|`limit`|`ordering`|`results`|`count`|
|`pulp/api/v3/pulp_container/namespaces/`|`offset`|`limit`|**`sort`**|`results`|`count`|
|`pulp/api/v3/remotes/ansible/collection/`|`offset`|`limit`|`ordering`|`results`|`count`|
|`pulp/api/v3/repositories/ansible/ansible/`|`offset`|`limit`|`ordering`|`results`|`count`|
|`pulp/api/v3/repositories/container/container-push/`|`offset`|`limit`|`ordering`|`results`|`count`|
|`pulp/api/v3/roles/`|`offset`|`limit`|`ordering`|`results`|`count`|
|`pulp/api/v3/signing-services/`|`offset`|`limit`|`ordering`|`results`|`count`|
|`pulp/api/v3/tasks/`|`offset`|`limit`|`ordering`|`results`|`count`|
|`v1/imports/`|**`page`**|**`page_size`**|**`order_by`**|`results`|`count`|
|`v1/namespaces/`|**`page`**|**`page_size`**|**`sort`**|`results`|`count`|
|`v1/roles/`|**`page`**|**`page_size`**|**`order_by`**|`results`|`count`|
|`v3/plugin/ansible/search/collection-versions/`|`offset`|`limit`|**`order_by`**|`data`|`meta.count`|
|`v3/plugin/execution-environments/repositories/`|`offset`|`limit`|**`sort`**|`data`|`meta.count`|
|`v3/tasks/`|`offset`|`limit`|**`sort`**|`data`|`meta.count`|
